[package]
name = "zust-vm-spirv"
version = "0.9.6"
edition = "2024"
rust-version = "1.85"
description = "SPIR-V code generation backend for the Zust scripting language."
license = "Apache-2.0"
repository = "https://github.com/zhuchuanjing/zust"
homepage = "https://www.zust-lang.com"
keywords = ["zust", "spirv", "gpu"]
categories = ["compilers", "rendering"]

[lib]
name = "vm_spirv"

[dependencies]
anyhow = "1.0.102"
compiler = { package = "zust-compiler", version = "0.9.23", path = "../compiler" }
dynamic = { package = "zust-dynamic", version = "0.9.10", path = "../dynamic" }
parser = { package = "zust-parser", version = "0.9.9", path = "../parser" }
rspirv = "0.13.0"
smol_str = "0.3.6"
spirv = "0.4.0"

[[example]]
name = "vm_spirv_bitonic"
path = "examples/bitonic.rs"

[[example]]
name = "vm_spirv_dump_mandel"
path = "examples/dump_mandel.rs"

[[example]]
name = "vm_spirv_mandelbrot"
path = "examples/mandelbrot.rs"

[[example]]
name = "vm_spirv_pathfind"
path = "examples/pathfind.rs"

[[example]]
name = "vm_spirv_poly"
path = "examples/poly.rs"
