[package]
name = "zust-dynamic"
version = "0.9.28"
edition = "2024"
rust-version = "1.85"
description = "Dynamic value model for Zust scripts, with JSON, MessagePack, bytes, and typed vectors."
license = "Apache-2.0"
repository = "https://github.com/zhuchuanjing/zust"
homepage = "https://www.zust-lang.com"
keywords = ["zust", "dynamic", "runtime"]
categories = ["compilers", "data-structures"]

[lib]
name = "dynamic"

[dependencies]
tinyvec = { version = "1.11.0", features = ["alloc"] }
bytemuck = { version = "1.25.0", features = ["extern_crate_alloc"] }
ordered-float = "5.3.0"
anyhow = "1.0.102"
thiserror = "2.0.18"
smol_str = "0.3.6"
indexmap = "2.14.0"
byteorder = "1.5.0"
hex = "0.4.3"
bitvec = "1.0.1"
half = "2.7.1"
parking_lot = "0.12.3"

serde_json="1.0.149"
