[package]
name = "zust-compiler"
version = "0.9.4"
edition = "2024"
rust-version = "1.85"
description = "Compiler front-end and semantic lowering for the Zust scripting language."
license = "Apache-2.0"
repository = "https://github.com/zhuchuanjing/zust"
keywords = ["zust", "compiler", "language"]
categories = ["compilers"]

[lib]
name = "compiler"

[dependencies]
dynamic = { package = "zust-dynamic", version = "0.9.4", path = "../dynamic" }
parser = { package = "zust-parser", version = "0.9.2", path = "../parser" }

log = "0.4.29"
anyhow = "1.0.102"
thiserror = "2.0.18"
smol_str = "0.3.6"
indexmap = "2.14.0"
