[package]
name = "zusts"
version = "0.9.3"
edition = "2024"
publish = false

[dependencies]
dynamic = { package = "zust-dynamic", version = "0.9.4", path = "../dynamic" }
parser = { package = "zust-parser", version = "0.9.4", path = "../parser" }
compiler = { package = "zust-compiler", version = "0.9.6", path = "../compiler" }
root = { package = "zust-root", version = "0.9.2", path = "../root" }
vm = { package = "zust-vm", version = "0.9.11", path = "../vm", features = ["ir-disassembly"] }
vm-spirv = { package = "zust-vm-spirv", version = "0.9.2", path = "../vm-spirv" }
vulkan = { package = "zust-vulkan", version = "0.9.2", path = "../vulkan" }
llm = { package = "zust-llm", version = "0.9.4", path = "../llm" }
anyhow = "1.0.102"
smol_str = "0.3.6"
cranelift = "0.131.1"
image = "0.25.10"
bytemuck = "1.25.0"
vulkano = "0.35.2"

rand = "0.10.1"

tokio = {version = "1.52.3", features = ["full"]}
futures = "0.3.32"

[dev-dependencies]
num-bigint = "0.4.6"
num-rational = "0.4.2"
num-traits = "0.2.19"
