[package]
name = "zust-vulkan"
version = "0.9.4"
edition = "2024"
rust-version = "1.85"
description = "Vulkan execution helpers for Zust SPIR-V kernels."
license = "Apache-2.0"
repository = "https://github.com/zhuchuanjing/zust"
homepage = "https://www.zust-lang.com"
keywords = ["zust", "vulkan", "gpu"]
categories = ["rendering"]

[lib]
name = "vulkan"

[dependencies]
anyhow = "1.0.102"
bytemuck = "1.25.0"
image = "0.25.10"
vulkano = "0.35.2"

[dev-dependencies]
vm-spirv = { package = "zust-vm-spirv", version = "0.9.5", path = "../vm-spirv" }

[[example]]
name = "vulkan_run_bitonic"
path = "examples/run_bitonic.rs"

[[example]]
name = "vulkan_run_mandel"
path = "examples/run_mandel.rs"

[[example]]
name = "vulkan_run_pathfind"
path = "examples/run_pathfind.rs"

[[example]]
name = "vulkan_run_poly"
path = "examples/run_poly.rs"
