[package]
name = "zust-vm-metal"
version = "0.9.10"
edition = "2024"
rust-version = "1.85"
description = "Metal shader source generation backend for the Zust scripting language."
license = "Apache-2.0"
repository = "https://github.com/zhuchuanjing/zust"
homepage = "https://www.zust-lang.com"
keywords = ["zust", "metal", "gpu"]
categories = ["compilers", "rendering"]

[lib]
name = "vm_metal"

[features]
default = ["runtime"]
runtime = ["dep:bytemuck", "dep:metal", "dep:objc"]

[dependencies]
anyhow = "1.0.102"
bytemuck = { version = "1.25.0", optional = true }
compiler = { package = "zust-compiler", version = "0.9.35", path = "../compiler" }
dynamic = { package = "zust-dynamic", version = "0.9.17", path = "../dynamic" }
image = "0.25.10"
metal = { version = "0.33.0", optional = true }
objc = { version = "0.2.7", optional = true }
parser = { package = "zust-parser", version = "0.9.16", path = "../parser" }
smol_str = "0.3.6"

[dev-dependencies]
vm = { package = "zust-vm", version = "0.9.76", path = "../vm" }

[[example]]
name = "vm_metal_bitonic"
path = "examples/bitonic.rs"

[[example]]
name = "vm_metal_run_mandel"
path = "examples/run_mandel.rs"
