[package]
name = "zust-bench"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "bench"
path = "src/main.rs"

[[bin]]
name = "bug-demo"
path = "src/bug_demo.rs"

[[bin]]
name = "debug-sieve"
path = "src/debug_sieve.rs"

[[bin]]
name = "spectral_concurrent"
path = "src/spectral_concurrent.rs"

[dependencies]
dynamic = { package = "zust-dynamic", version = "0.9.20", path = "../dynamic" }
vm = { package = "zust-vm", version = "0.9.91", path = "../vm" }
anyhow = "1.0.102"
