[package]
name = "zust-lsp"
version = "0.9.2"
edition = "2024"
publish = false

[dependencies]
compiler = { package = "zust-compiler", version = "0.9.2", path = "../compiler" }
dynamic = { package = "zust-dynamic", version = "0.9.2", path = "../dynamic" }
parser = { package = "zust-parser", version = "0.9.2", path = "../parser" }
dashmap = "7.0.0-rc2"
serde_json = "1.0.149"
tokio = { version = "1.52.3", features = ["full"] }
tower-lsp = "0.20.0"
